name: "readme"

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  readme:
    name: "readme"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: kafkiansky
          commit_user_email: vadimzanfir@gmail.com
          commit_author: kafkiansky <vadimzanfir@gmail.com>
